### ISSUE TITLE
앱바에 타이틀 수정 요구사항

### ISSUE THREAD

**Issue by JAECHON-YU** [playground-code-review/flutter#12]
현재 앱바에 타이틀이 Flutter Demo Home Page 로 되어 있습니다.

PlayGround  로 수정해주시기 바랍니다^^

**Comment by deviankim** [comment]
이슈 생성 감사드립니다. 덕분에 영상도 찍고 다른 분들 PR 연습에 많은 도움 되었으리라 믿습니다.
