### ISSUE TITLE
+ 버튼 클릭시 +2씩 증가

### ISSUE THREAD

**Issue by deviankim** [playground-code-review/flutter#2]
고객사 요청으로 +1씩 증가하던 것을 +2씩 증가해야 합니다.

PR 생성 가이드 - https://youtu.be/eCl3oVq0EoY

**Comment by JAECHON-YU** [comment]
ㅋ $githubid 보고  아!! 역시 개발자라고 감탄 중!!

**Comment by JAECHON-YU** [comment]
#4 
여기 권기원님이 올린 PR 로 해결이 가능해보입니다..ㅋㅋ

**Comment by deviankim** [comment]
> #4
> 여기 권기원님이 올린 PR 로 해결이 가능해보입니다..ㅋㅋ

넵 감사합니다.
다른 분들도 어서 이 이슈에 대응하여 PR 올리기 연습하시고 올려주세요~
권기원님이 참 잘하셨습니다! 짝짝짝~

**Comment by deviankim** [comment]
> ㅋ $githubid 보고 아!! 역시 개발자라고 감탄 중!!

각자 fork 하는게 더 좋아서, 가이드 영상 찍어서 올리고, 기존 $githubid 관련 내용은 제거했습니다^^

**Comment by NakGun** [comment]
전 이슈 연결 버튼(설정버튼)이 안보이네요 ㅋ

**Comment by JAECHON-YU** [comment]
> 전 이슈 연결 버튼(설정버튼)이 안보이네요 ㅋ

설정아이콘 누르면 PR들 다 보여요^^

<img width="331" alt="스크린샷 2021-01-10 오후 3 52 26" src="https://user-images.githubusercontent.com/42856326/104116446-ee4bb380-535b-11eb-8fc6-b72874a1e79d.png">

**Comment by deviankim** [comment]
> 전 이슈 연결 버튼(설정버튼)이 안보이네요 ㅋ

그러네요. 이게 공동 작업자로 초대가 되어야지만 보이네요. 영상에다가 설명 보충해야겠습니다.
피드백 감사합니다.
