### ISSUE TITLE
사전과제2 테스트 나누기

### ISSUE THREAD

**Issue by deviankim** [playground-code-review/flutter#37]
하나의 테스트 모듈에 여러 가지의 테스트가 포함되어 있습니다.

항목별로 분리할 필요가 있습니다.

* 다소 도전적인 요소가 있을 수 있습니다. github 를 통한 커뮤니케이션으로 풀어나가기를 기대합니다.

**Comment by kindkmj** [comment]
항목별로 분리한다는게 그냥 단순히 기능들을 함수로 묶는건가요? 
flutter 에서테스트 코드 짰을때 저는 테스트에다가 다 때려만 박아봐서 ㅜㅜ

**Comment by deviankim** [comment]
> 항목별로 분리한다는게 그냥 단순히 기능들을 함수로 묶는건가요?
> flutter 에서테스트 코드 짰을때 저는 테스트에다가 다 때려만 박아봐서 ㅜㅜ

https://github.com/playground-code-review/flutter/blob/master/test/widget_test.dart

현재 테스트 코드가 하나의 모듈에 이것 저것 다 테스트하도록 구성되어 있거든요.

이것을 여러 모듈로 분리해서 하나씩 테스트하도록 하자는 이슈입니다.
