### ISSUE TITLE
- 버튼 클릭시 -2씩 감소

### ISSUE THREAD

**Issue by jimingoal** [playground-code-review/flutter#9]
고객사 요청으로 -버튼을 생성하고 버튼 클릭시 -2씩 감소해야 합니다.

**Comment by deviankim** [comment]
> 고객사 요청으로 -버튼을 생성하고 버튼 클릭시 -2씩 감소해야 합니다.

요구사항 질문입니다.
그럼 기존 + 버튼을 유지하고, - 버튼을 추가해야 하는거죠?
위치는 연습이니 자유롭게 하면 될 것 같습니다만..

**Comment by jimingoal** [comment]
요구사항 
- '+' 버튼을 유지합니다.
- '+' 버튼과 -버튼을 수직으로 배치합니다. 
- 버튼 컬러는 + blue / - red로 합니다. 

너무 인위적인 요구사항인가요 ^^;

**Comment by deviankim** [comment]
> 요구사항
> 
> * '+' 버튼을 유지합니다.
> * '+' 버튼과 -버튼을 수직으로 배치합니다.
> * 버튼 컬러는 + blue / - red로 합니다.
> 
> 너무 인위적인 요구사항인가요 ^^;

매우 좋습니다. 요구사항은 논란의 여지가 없도록 구체적일수록 좋죠.
